# Generated by Django 2.2.7 on 2019-11-27 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(default=None, max_length=255)),
                ('contact', models.BigIntegerField(default=None, max_length=10)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('booking_id', models.PositiveIntegerField(blank=True, default=0)),
                ('Intime_booking', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Host_Details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
