# Generated by Django 2.2.7 on 2019-11-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Intime_booking',
        ),
    ]
