# Generated by Django 2.2.7 on 2019-11-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_remove_appointment_intime_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_status',
            field=models.CharField(blank=True, default='Pending', max_length=255),
        ),
    ]
